# Generated by Django 5.2.6 on 2025-10-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='autor',
            new_name='user',
        ),
    ]
